tokens = (
    'ID', 'NUM_INT', 'NUM_DEC', 'TEXTO',
    'SEMICOLON', 'DOT', 'COMMA','PLUSPLUS','MINUSMINUS', 'MODULO',
    'PLUS', 'MINUS', 'TIMES', 'DIVIDE', 'EQUALS', 
    'LPAREN', 'RPAREN', 'LBRACE', 'RBRACE', 'LBRACKET', 'RBRACKET',
    'OROR', 'ANDAND', 'GREATER', 'LESS', 'GREATEREQUAL', 'LESSEQUAL', 'NOTEQUAL', 'EQUAL',
    'PLUSEQUAL', 'MINUSEQUAL', 'TIMESEQUAL', 'DIVEQUAL', 'ANDANDEQUAL', 'OROREQUAL',
    'COMMENT', 'MULTICOMMENT', 'WHILE' , 'FOR', 'IF', 'ELSE', 'RETURN', 'STRUCT'
)